# Generated by Django 5.2.9 on 2025-12-15 20:00

import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=80)),
                ('job_title', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('sur_name', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('date_of_birth', models.DateField(validators=[employees.models.validate_age_18])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('pay_type', models.CharField(choices=[('SALARY', 'Salary'), ('HOURLY', 'Hourly')], max_length=10)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('user', models.OneToOneField(blank=True, help_text='Linked login account (optional until created).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hire', models.DateField()),
                ('salary_type', models.CharField(choices=[('SALARY', 'Salary'), ('HOURLY', 'Hourly')], max_length=10)),
                ('base_pay', models.DecimalField(decimal_places=2, help_text='Annual salary or hourly rate depending on pay type.', max_digits=10)),
                ('medical', models.CharField(choices=[('SINGLE', 'Single'), ('FAMILY', 'Family')], default='SINGLE', max_length=10)),
                ('dependents', models.PositiveIntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profile', to='employees.employee')),
            ],
        ),
    ]
