# Generated by Django 5.2.9 on 2025-12-15 21:13

import security.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=80, validators=[security.validators.validate_safe_name]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=80, validators=[security.validators.validate_safe_name]),
        ),
    ]
