# Generated by Django 5.2.9 on 2025-12-15 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_first_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pto_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='employees.employee')),
            ],
            options={
                'ordering': ['-work_date'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
