# Generated by Django 5.2.9 on 2025-12-15 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_first_name_alter_employee_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pretax_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_wages', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('state_tax_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('federal_tax_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('social_security_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicare_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('federal_tax_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('social_security_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicare_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paychecks', to='payroll.payrollrun')),
            ],
        ),
    ]
